#!/bin/bash -ex
#
# download a github project into default project dir and open
# Author: Dave Hulihan
#
# $ gp some-user/some-project.git


# This it what we should open the go project with
INIT_PROJECT_CMD="tmux-session"

# sanitize input, https://github.com/bvwells/go-present -> bvwells/go-present and git@github.com:bvwells/go-present.git -> bvwells/go-present
if [[ -z $1 ]] ; then
  echo "usage: gp some-user/some-project"
  return
fi

if [[ $1 == *".git" ]] ; then
  # strip off trailing .git
  set -- "${1%.git}"
fi

if [[ $1 == *"github.com"* ]] ; then
  set -- "${1#*github.com[:\/]}"
fi

GIT_REPO="https://github.com/${1}.git"

echo "cloning repo ($1): ${GIT_REPO}"
return

cd $PROJECTS
git clone $GIT_REPO

if [[ $? -ne 0 ]] ; then
  warn "failed to clone repo ${GIT_REPO}"
  return
fi

PROJECT_NAME=$(basename $1)
cd $PROJECT_NAME

# don't start up the project if we're already in tmux
if [[ -z $TMUX ]] ; then
  $INIT_PROJECT_CMD
fi
