#!/bin/zsh
#
# create directory and move file into it
# NOTE: <dst> should be a directory, not a file
# 
if [[ -z $2 ]]; then
	echo "$0 <src> <dst>"  
	exit 1
fi 

DESTDIR=$2
mkdir -p $DESTDIR && mv $1 $DESTDIR
