#!/bin/bash
#
# tmux-session [existing-session-name]
#
# Author: Dave Hulihan <dhulihan@gmail.com>
# Description: Create/attach tmux session based on project directory
#
# * existing-session-name - omit to create a new session based on the name of
# your current directory


# don't do anything if we're already in tmux
if [[ -v TMUX ]] ; then
  debug "already in tmux"
  return
fi

export EDITOR_CMD="nvim4"
BASENAME=$(basename $PWD)
SESSION_NAME_RAW=${1:-$BASENAME}
SESSION_NAME=$(gecho -n $SESSION_NAME_RAW | sed 's/\.//g')

echo "creating session $SESSION_NAME"


# set iterm2 color
case $SESSION_NAME in
  dotfiles)
    TAB_COLOR=black
    TAB_EMOJI=$(emoji-hash ${SESSION_NAME})
    ;;
  secrets)
    TAB_COLOR=yellow
    TAB_EMOJI=🔒
    ;;
  staging)
    TAB_COLOR=orange
    TAB_EMOJI=🏖️
    ;;
  prod)
    TAB_COLOR=red
    TAB_EMOJI=⚠️
    ;;
  explore)
    TAB_COLOR=black
    TAB_EMOJI=🔎
    ;;
  dev)
    TAB_COLOR=purple
    TAB_EMOJI=$(emoji-hash ${SESSION_NAME})
    ;;
  *)
    # color by project type
    TAB_COLOR=$(color)
    TAB_EMOJI=$(emoji-hash ${SESSION_NAME})
    ;;
esac

# set iterm2 title
iterm-tab-title "${TAB_EMOJI} ${SESSION_NAME}"
iterm-tab-color $TAB_COLOR

# attempt to attach to
tmux a -t "=${SESSION_NAME}"

if [[ $? -ne 0 ]] ; then
  debug "cannot find existing session, creating a new session"
  tmux new -s $SESSION_NAME -d

  # create windows
  case $SESSION_NAME in
    Notes|explore)
      # no shell session, only editor
      EDITOR_WINDOW=1
      ;;
    prod|staging)
      # no editor session, only shell
      SHELL_WINDOW=1
      ;;
    *)
      tmux new-window -t $SESSION_NAME -n vim

      # open vim on second window
      SHELL_WINDOW=1
      EDITOR_WINDOW=2

      ;;
  esac

  # setup windows
  if [[ ! -z $EDITOR_WINDOW ]] ; then
    tmux send-keys -t $SESSION_NAME:$EDITOR_WINDOW $EDITOR_CMD C-m
    tmux select-window -t $SESSION_NAME:$EDITOR_WINDOW
  fi

  # attach to session
  tmux a -t $SESSION_NAME
fi
